### ISSUE TITLE
Not work on Mac OS X

### ISSUE THREAD

**Issue by zguangyu0000** [jmoon018/PacVim#18]
I can compile it with clang without errors. It shows "Level 0" and tells me to press Enter and then I win. I can not see the map or pacman or monsters. It may be caused by different implementation of ncurses library.

**Comment by jmoon018** [comment]
@zguangyu0000 

I am not 100% sure what is causing the problem, but it is possible that part of the issue involves curses as you mentioned. There are two ways in which someone wins the game: 
1.  if the `&` key is pressed -- which is not the case here
2.  if the player's current points are equal to the TOTAL_POINTS -- current points starts at zero and increments with each letter the player steps on, and TOTAL_POINTS is initially zero, and increments by the amount of letters in the map (in the `drawScreen` method) when the game loads

You mentioned that you do not see the map, so the map never gets drawn. If the map doesn't get drawn, the TOTAL_POINTS never increments and stays at zero. This meets the win condition, instantly, and is maybe why immediately win the game upon pressing enter. 

By fixing the issue of the map not getting drawn, I *think* the other issue of winning the game instantly should be alleviated

I can think of two reasons why the map isn't getting drawn: different curses implementation, or the map is never loaded properly. For now, go to the folder where you cloned PacVim, type `make MAPDIR=maps` and try playing again. This will change where the maps are loaded from.

If that doesn't work, I'll try to reproduce the bug on my computer tomorrow. I may have to change the game files so I create more meaningful logs.. I can then inspect your logs and try to track it down.

**Comment by jmoon018** [comment]
@zguangyu0000 

I tried it on OS X. I was able to reproduce the bug, but only when I write `make`
When type `make install`, everything works fine. If you haven't done so yet, be sure to use `make install` and let me know how that goes

**Comment by diimdeep** [comment]
use `brew install pacvim`

**Comment by ghecho** [comment]
Yes, as @jmoon018 says, <code>make install</code> solves the problem. BTW great game. Frustratingly fun! but I'm getting better.

**Comment by jmoon018** [comment]
@ghecho 

Thanks for confirming the fix, and yes, the game can be pretty damn hard, even for me. I'd recommend changing the `THINK_MULTIPLIER` constant in `globals.cpp`. Increasing it from 1.0 to 1.20 will make the ghosts move 20% slower, etc. I probably should have made a normal and hard mode via command line arguments a long time ago

Anyway, closing since this particular issue is resolved.

**Comment by Gabrielvon** [comment]
@diimdeep I did install it with brew but still have the same issues.

@jmoon018 I am not able to install the pacvim on my mac sierra with the alternative method.

```
$ git clone https://github.com/jmoon018/PacVim.git
$ cd PacVim
$ sudo make install
```

It seems in my mac there has no `-D` and `-t` option for the `make install` command.
